### ISSUE TITLE
Please mention that forecast will not work on free plan

### ISSUE THREAD

**Issue by blackbyte-pl** [farahat80/react-open-weather#15]
Daily forecast is available only on paid plans on Open Weather Map API. Please mention that somewhere before somebody will waste too much time trying to configure that.

**Comment by farahat80** [comment]
@blackbyte-pl the component now is using openweather api instead of the new weatherStack, on openweather api the current and forecast is available on the free plan for up to 1000 calls per day

**Comment by farahat80** [comment]
i am currently working on version 1.0 which will decouple the data provider from the component allowing the component to work with multiple providers while also giving freedom for others to write their own custom providers

**Comment by blackbyte-pl** [comment]
Hi,
You are using /forecast/daily which seems to be available only for paid plans. 
https://openweathermap.org/api

**Comment by farahat80** [comment]
i just realised that for some reason /daily is available to me, i am not a paid user but i had a very old account with openweather, may old user used to have the 16 day forecast for free, now i see that only the 5 days are free which is fine since that is what we need for the component

Thanks @blackbyte-pl for pointing that, i will work on a fix right away

**Comment by blackbyte-pl** [comment]
The problem with 5 days forecast is that is given within 3h intervals, there is no daily summary. This is still doable but makes harder to decide whatever icon (weather condition) to display as it might change

**Comment by farahat80** [comment]
yes I just realized that now from the docs, I will have to think of a solution around that, meaniwhile i will add a note in the readme, so that people are aware of this
