### ISSUE TITLE
fix the forecast endpoint to allow the component to function for free plan

### ISSUE THREAD

**Issue by farahat80** [farahat80/react-open-weather#16]
The current forecast endpoint is using the 16 days forecast which is only for paid users, the component only need the 5 days forecast to function, so the endpoint need to be changed in the code to allow the component to be used with the free plan

**Comment by craigyu** [comment]
Hello, love the widget, please fix the api call soon.

It should be `http://api.openweathermap.org/data/2.5/forecast?appid=4xxxxxxxxxxxxxxxxxxxx6`
instead of `http://api.openweathermap.org/data/2.5/current/daily?appid=4xxxxxxxxxxxxxxxxxxxx6`

cheers

**Comment by craigyu** [comment]
sorry. what i meant was it should be that instead of `http://api.openweathermap.org/data/2.5/forecast/daily?appid=4xxxxxxxxxxxxxxxxxxxx6`

Here's the file i fixed along with `  _map(forecastData, todayData, lang)` updates

```
import axios from 'axios';
import utils from './utils';

export default class OpenWeatherApi {
  constructor(unit, apiKey, lang) {
    this.unit = unit;
    this.apiKey = apiKey;
    this.baseApiUrl = '//api.openweathermap.org/data/2.5';
    this.lang = lang;
  }
  getForecast(args) {
    const endpointForecast = `${this.baseApiUrl}/forecast`;
    const endPointToday = `${this.baseApiUrl}/weather`;
    const params = Object.assign(
      {
        appid: this.apiKey,
        cnt: 5,
        lang: this.lang,
        units: this.unit,
      },
      args
    );

    const promise = axios
      .all([
        axios.get(endpointForecast, { params }),
        axios.get(endPointToday, { params }),
      ])
      .then(
        axios.spread((forecastReponse, todayReponse) => {
          const forecastData = forecastReponse.data;
          const todayData = todayReponse.data;
          if (forecastData && todayData) {
            return this._map(forecastData, todayData, params.lang);
          }
          return {};
        })
      );
    return promise;
  }
  _map(forecastData, todayData, lang) {
    const daysData = forecastData.list;
    const mapped = {};
    mapped.location = forecastData.city;
    mapped.days = daysData.map(item => ({
      date: utils.formatDate(item.dt, lang),
      description: item.weather[0] ? item.weather[0].main : null,
      icon: item.weather[0] ? item.weather[0].icon : null,
      temperature: {
        min: item.main.temp_min.toFixed(0),
        max: item.main.temp_max.toFixed(0),
      },
      wind: item.wind.speed.toFixed(0),
      humidity: item.main.humidity,
    }));
    if (mapped.days.length > 0) {
      mapped.days[0].temperature.current = todayData.main.temp.toFixed(0);
    }
    return mapped;
  }
}
```

**Comment by VladLegkowski** [comment]
@craigyu +1

**Comment by ClementL33** [comment]
Thanks @craigyu for the fix, and yes this has to be updated.

(keywords for users searching the infinite loading issue):
401, unauthorized, infinite, loading, stuck, doesn't, issue, working, work, loading...

**Comment by ClementL33** [comment]
Can you guys explain how you made the changes?

I've been in node_modules/react-open-weather/ and edited anywhere `/daily` appeared, plus replaced the `OpenWeatherApi.js` content with your @craigyu 

And I have that same 401 error with a `/daily` in the call URL
Thanks!
