### ISSUE TITLE
No image is shown for some weather types.

### ISSUE THREAD

**Issue by andreasviklund** [farahat80/react-open-weather#3]
When the weather is "Light snow" no image is shown on the component:

![2018-03-05 16_45_20-gordon delivery - admin portal](https://user-images.githubusercontent.com/1401636/36984257-c251ada4-2094-11e8-90dd-569baef1a8c4.png)

Same goes for "Light freezing rain".

**Comment by farahat80** [comment]
Fixed with https://github.com/farahat80/react-open-weather/pull/5
