### ISSUE TITLE
I want to change the background color 

### ISSUE THREAD

**Issue by khawarqureshi** [farahat80/react-open-weather#72]
I have used custom styling to change the background color, text color, and icon color as well by using !important. but there is no chance to override the style as the class name is changing every time on refresh. How to apply your own styling to this component. Is there any way to do that?

**Comment by farahat80** [comment]
@khawarqureshi just released 1.1.6, now all building blocks has one extra fixed class name to solve this problem

**Comment by khawarqureshi** [comment]
I really appreciate that
