### ISSUE TITLE
SVG PATH issues

### ISSUE THREAD

**Issue by patrickellis** [farahat80/react-open-weather#76]
Not necessarily an issue with the plugin, but I'm having trouble passing in an SVG PATH in a custom data object, everything else renders fine. 
Can you clarify what to pass in and how to load it in react?

Tried referencing svgs within react /assets, passing an SVG react component, etc.

**Comment by farahat80** [comment]
@patrickellis can you give more explanation on what are you trying to achieve, what should this SVG do inside the component?
