### ISSUE TITLE
Getting weather to refresh

### ISSUE THREAD

**Issue by EverettMcKay** [farahat80/react-open-weather#77]
I would like the weather tile to periodically refresh to show the current weather. Tried everything I could think of without success. React seems to think the useOpenWeather call is a hook, which doesn't help because that means I can't wrap it in useEffect or give it a dependency array.

Is there a recommended way to get react-open-weather to refresh periodically based on a timer?

**Comment by farahat80** [comment]
@EverettMcKay the 2 hooks useOpenWeather and useWeatherbit both has a function called **fetchData** which can be used to refetch the data again, for example

`const { data, isLoading, errorMessage, fetchData } = useOpenWeather({})`

you can use this function in a **useEffect** with a timer to trigger refresh in the intervals you need

**Comment by EverettMcKay** [comment]
That's it! Brilliant! Thanks, Ahmed.
