### ISSUE TITLE
Network Error on call useOpenWeather

### ISSUE THREAD

**Issue by radekzz** [farahat80/react-open-weather#80]
First of all, great job!!!

I have a problem when implemented a component, i'm getting **Network Error**.
There is a blank page on screen and this error in console. This error disappear when i remove constant assignment.

Steps to reproduce in React Native app:

`import ReactWeather, { useOpenWeather } from 'react-open-weather';`

```
const { data, isLoading, errorMessage } = useOpenWeather({
    key: 'API-KEY',
    lat: '48',
    lon: '11',
    lang: 'en',
    unit: 'metric',
  });
```

```
<ReactWeather
          isLoading={isLoading}
          errorMessage={errorMessage}
          data={data}
          lang="en"
          locationLabel="Munich"
          unitsLabels={{ temperature: 'C', windSpeed: 'Km/h' }}
          showForecast
        />
```

**Comment by farahat80** [comment]
@radekzz can you provide the error message?, looks to me like something is blocking the connection from your browser

**Comment by baur** [comment]
error from console
http://api.openweathermap.org/data/2.5/onecall?appid={mykey}&lang=ru&units=metric&lat=51.1277&lon=71.4283

{"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}

But I'm passing 100% right API

**Comment by baur** [comment]
Possible reason:

> You are using a Free subscription and try requesting data available in other subscriptions . For example, [16 days/daily forecast API](https://openweathermap.org/forecast16), [any historical weather data](https://openweathermap.org/price#history), [Weather maps 2.0](https://openweathermap.org/api/weather-map-2), etc). Please, check your subscription in your [personal account](https://home.openweathermap.org/)


![image](https://user-images.githubusercontent.com/2898361/195766233-3b43e409-063a-40b8-b01f-d4d6154f3af8.png)
