### ISSUE TITLE
Themes do not work

### ISSUE THREAD

**Issue by daniiy01** [farahat80/react-open-weather#99]
Hi, I need to be able to change the svg colour to white and I can't get the themes to work. I created one following your Readme.md example and I can't get the defined colours to work. What could it be due to?
When reloading the browser, as far as I can briefly see, I think it loads the colours, but after a few tenths of a second it overwrites it.

(I do not put code as it is literally a copy paste of your example.)

PD: I am getting the following error in the browser console (Irrespective of whether or not I put up the themes)
![image](https://user-images.githubusercontent.com/78351496/178974185-eaf1dbb2-5d01-45c0-b048-53e751ae7d95.png)

Thanks in advance.

**Comment by ygua699** [comment]
Are you using typescript for your react project?

**Comment by daniiy01** [comment]
> Are you using typescript for your react project?
> 
> I got the same issue when I was doing local development, but it works fine after deploying it.
> 
> ![image](https://user-images.githubusercontent.com/62586556/180640272-053539e7-546a-4f8b-b3b8-5441cf07a6ef.png)

Hello. Yes I am using typescript but I have not yet tried to test it outside Visual Studio. I'm still developing it. I'll try it when I have everything finished. Thank you very much!

**Comment by uriya4647** [comment]
hi 
there is me also the same problem, what is the solution, I cannot understand?

**Comment by farahat80** [comment]
Can anyone provide a codesandbox or something similar that shows the problem, testing on version 1.2.1 and i can modify the theme accordingly without a problem.

would also be helpful to know what Node and webpack version you are using.

**Comment by farahat80** [comment]
Issue fixed with v1.3.0
